# Base dirs
WORKDIR = 'home/lukas/lstm-irgan'
TEMP = WORKDIR + '/TEMP/'
GAN_MODEL_BEST_FILE = TEMP + 'gan_model'

# Discriminator
DISC_TRAIN_EPOCHS = 100
DISC_HIDDEN_SIZE = 46
DISC_WEIGHT_DECAY = 0.01
DISC_LEARNING_RATE = 0.001
DISC_TEMPERATURE = 0.2
DISC_BATCH_SIZE = 8

# Generator
GEN_TRAIN_EPOCHS = 10
GEN_HIDDEN_SIZE = 46
GEN_WEIGHT_DECAY = 0.01
GEN_LEARNING_RATE = 0.001
GEN_TEMPERATURE = 0.2
GEN_BATCH_SIZE = 8
GEN_LAMBDA = 0.5

# MQ2008 data
MQ2008_FEATURE_SIZE = 46

NORM_DATA_FILE = WORKDIR + '/MQ2008_test/Large_norm.txt'
TRAIN_DATA_FILE = WORKDIR + '/MQ2008_test/train.txt'
TEST_DATA_FILE = WORKDIR + '/MQ2008_test/test.txt'

# Data
MQ2008 = 'MQ2008'

# General
TRAIN_EPOCHS = 30
DATA = MQ2008
FEATURE_SIZE = MQ2008_FEATURE_SIZE

TRAIN_MODE = 'train'
EVAL_MODE = 'train'



